local items = {
    {
        Name = "医疗石",
        _desc = "免费采集到的有医疗效果的石头，吞食令人肚子痛",
        Art = "ReplaceableTextures\\CommandButtons\\BTNHealthStone.blp",
        goldcost = 0,
        lumbercost = 0,
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        cooldown = 70,
        _active = "使用后在10秒内持续恢复共200点生命",
        _overlie = 99,
        _weight = 0.1,
        Hotkey = "Q",
    },
    {
        Name = "魔法石",
        _desc = "免费采集到的有智慧的石头，据说只有变态魔法师服用",
        Art = "ReplaceableTextures\\CommandButtons\\BTNManaStone.blp",
        goldcost = 0,
        lumbercost = 0,
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        cooldown = 70,
        _active = "使用后在10秒内持续恢复共150点魔法",
        _overlie = 99,
        _weight = 0.1,
        Hotkey = "W",
    },
    {
        Name = "医疗剂",
        _desc = "轻松制得的医疗药水，奸商卖得并不便宜",
        Art = "ReplaceableTextures\\CommandButtons\\BTNHealingSalve.blp",
        goldcost = 50,
        lumbercost = 0,
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        cooldown = 40,
        _active = "使用后在6秒内持续恢复共500点生命",
        _overlie = 99,
        _weight = 0.1,
        Hotkey = "E",
    },
    {
        Name = "魔法剂",
        _desc = "轻松制得的魔法药水，奸商卖得也不便宜",
        Art = "ReplaceableTextures\\CommandButtons\\BTNVialFull.blp",
        goldcost = 50,
        lumbercost = 0,
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        cooldown = 40,
        _active = "使用后在6秒内持续恢复共300点魔法",
        _overlie = 99,
        _weight = 0.1,
        Hotkey = "R",
    },
    {
        Name = "吸血药水",
        _desc = "吸血魔鬼的药水",
        Art = "ReplaceableTextures\\CommandButtons\\BTNPotionOfVampirism.blp",
        goldcost = 100,
        lumbercost = 0,
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        cooldown = 60,
        _active = "使用后在35秒内增加20%吸血",
        _overlie = 9,
        _weight = 0.1,
        Hotkey = "A",
    },
    {
        Name = "完美药水",
        _desc = "996福报药水",
        Art = "ReplaceableTextures\\CommandButtons\\BTNSnazzyPotion.blp",
        goldcost = 996,
        lumbercost = 0,
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        cooldown = 60,
        _active = "使用后瞬间恢复所有生命和魔法",
        _overlie = 9,
        _weight = 0.1,
        Hotkey = "S",
    },
    {
        Name = "恢复卷轴",
        _desc = "一票保全家",
        Art = "ReplaceableTextures\\CommandButtons\\BTNScrollOfRegenerationGreen.blp",
        goldcost = 300,
        lumbercost = 0,
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        cooldown = 90,
        _active = "使用后600范围内的友军瞬间恢复300生命",
        _overlie = 3,
        _weight = 0.2,
        Hotkey = "D",
    },
    {
        Name = "加速卷轴",
        _desc = "忍者专用来逃跑的卷轴",
        Art = "ReplaceableTextures\\CommandButtons\\BTNScrollOfHaste.blp",
        goldcost = 300,
        lumbercost = 0,
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        cooldown = 90,
        _active = "使用后600范围内的友军提升移动力100点，攻速15%，持续30秒",
        _overlie = 3,
        _weight = 0.2,
        Hotkey = "F",
    },
    {
        Name = "枯枝",
        _desc = "树大有枯枝，枯枝997",
        Art = "ReplaceableTextures\\CommandButtons\\BTNNatureTouchGrow.blp",
        goldcost = 250,
        lumbercost = 0,
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        _overlie = 1,
        _weight = 0.3,
        Hotkey = "Z",
        _attr = {
            str_green = "+9",
            agi_green = "+9",
            int_green = "+7",
        }
    },
    {
        Name = "魔法师指环",
        _desc = "见习的魔法师都会佩戴的指环",
        Art = "ReplaceableTextures\\CommandButtons\\BTNRingJadeFalcon.blp",
        goldcost = 250,
        lumbercost = 0,
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        _overlie = 1,
        _weight = 0.1,
        Hotkey = "X",
        _attr = {
            mana = "+100",
            mana_back = "+1.8",
        }
    },
    {
        Name = "守护指环(劣质)",
        _desc = "精钢制造的指环，不过是劣质产出，效果一般",
        Art = "ReplaceableTextures\\CommandButtons\\BTNRingGreen.blp",
        goldcost = 300,
        lumbercost = 0,
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        _overlie = 1,
        _weight = 0.2,
        Hotkey = "C",
        _attr = {
            defend_green = "+4",
            damage_reduction = "+5",
        }
    },
    {
        Name = "铁靴",
        _desc = "沉重的铁靴，但冒险旅途艰难，有总比没有好",
        Art = "ReplaceableTextures\\CommandButtons\\BTNBootsOfSpeed.blp",
        goldcost = 550,
        lumbercost = 0,
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        _overlie = 1,
        _weight = 0.5,
        Hotkey = "V",
        _attr = {
            move = "+55",
        }
    },
}
local ids = ""
for _, v in ipairs(items) do
    local id = slkHelper.item.normal(v)
    if (ids == "") then
        ids = id
    else
        ids = ids .. "," .. id
    end
end

slkHelper.unit.shop({
    Name = "小神木商店",
    abilList = "Avul,Apit,Aneu",
    file = "buildings\\nightelf\\ChimaeraRoost\\ChimaeraRoost",
    Art = "ReplaceableTextures\\CommandButtons\\BTNResStone.blp",
    modelScale = 0.70,
    scale = 2.20,
    HP = 100,
    spd = 0,
    sight = 500,
    nsight = 500,
    unitSound = "",
    weapsOn = 0,
    race = "human",
    Sellitems = ids,
})