local couriers = {
    {
        Name = "呆萌的青蛙",
        Ubertip = "一只呆萌的青蛙，用蛙的胃袋携带物品",
        unitSound = "Frog",
        file = "units\\critters\\Frog\\Frog",
        Art = "ReplaceableTextures\\CommandButtons\\BTNHex.blp",
        modelScale = 1.50,
        scale = 1.20,
        moveHeight = 0,
        targType = "ground",
        armor = "Flesh",
        goldcost = 500,
        HP = 100,
        spd = 300,
        STR = 10,
        AGI = 5,
        INT = 3,
        STRplus = 0.6,
        AGIplus = 0.2,
        INTplus = 0.2,
    },
    {
        Name = "小饥鸡",
        unitSound = "Chicken",
        file = "units\\critters\\EasterChicken\\EasterChicken",
        Art = "ReplaceableTextures\\CommandButtons\\BTNCritterChicken.blp",
        modelScale = 1.40,
        scale = 1.20,
        moveHeight = 0,
        targType = "ground",
        armor = "Flesh",
        goldcost = 1000,
        HP = 150,
        spd = 330,
        STR = 14,
        AGI = 7,
        INT = 8,
        STRplus = 0.7,
        AGIplus = 0.3,
        INTplus = 0.2,
    },
    {
        Name = "冷静的绵羊",
        Ubertip = "一只冷酷的绵羊，用毛茸茸的白毛携带物品",
        unitSound = "Sheep",
        file = "units\\critters\\Sheep\\Sheep",
        Art = "ReplaceableTextures\\CommandButtons\\BTNSheep.blp",
        modelScale = 1.50,
        scale = 1.20,
        moveHeight = 0,
        targType = "ground",
        armor = "Flesh",
        goldcost = 2000,
        HP = 200,
        spd = 350,
        STR = 16,
        AGI = 12,
        INT = 10,
        STRplus = 0.8,
        AGIplus = 0.4,
        INTplus = 0.3,
    },
    {
        Name = "依诺吸吸",
        unitSound = "QuillBeast",
        file = "units\\critters\\Felboar\\Felboar",
        Art = "ReplaceableTextures\\CommandButtons\\BTNFelBoar.blp",
        modelScale = 1.40,
        scale = 1.20,
        moveHeight = 0,
        targType = "ground",
        armor = "Flesh",
        goldcost = 4000,
        HP = 500,
        spd = 380,
        STR = 24,
        AGI = 19,
        INT = 18,
        STRplus = 1.4,
        AGIplus = 0.9,
        INTplus = 0.8,
    },
    {
        Name = "灵动的雪鹰",
        unitSound = "SnowOwl",
        file = "units\\critters\\SnowOwl\\SnowOwl",
        Art = "ReplaceableTextures\\CommandButtons\\BTNSnowOwl.blp",
        modelScale = 1.20,
        scale = 1.20,
        movetp = "fly",
        moveHeight = 225.00,
        targType = "air",
        armor = "Flesh",
        goldcost = 8000,
        HP = 800,
        spd = 400,
        STR = 26,
        AGI = 22,
        INT = 20,
        STRplus = 1.8,
        AGIplus = 1.1,
        INTplus = 1.0,
    },
    {
        Name = "阴影之狼",
        unitSound = "Spiritwolf",
        file = "units\\orc\\Spiritwolf\\Spiritwolf",
        Art = "ReplaceableTextures\\CommandButtons\\BTNSpiritWolf.blp",
        modelScale = 1.20,
        scale = 1.20,
        targType = "ground",
        armor = "Flesh",
        goldcost = 15000,
        HP = 1200,
        spd = 420,
        STR = 30,
        AGI = 33,
        INT = 22,
        STRplus = 1.9,
        AGIplus = 1.5,
        INTplus = 1.1,
        weapTp1 = "normal",
        weapType1 = CONST_WEAPON_SOUND.WoodLightBash.value,
        cool1 = 2.0, -- 攻击周期
        backSw1 = 0.64, -- 攻击后摇
        dmgpt1 = 0.33, -- 攻击前摇
    },
}

-- courier
for _, v in ipairs(couriers) do
    v.isHero = 1
    v.race = "human"
    slkHelper.unit.courier(v)
end
