enemys = {
    {
        Name = "鬼影",
        file = "units\\undead\\Shade\\Shade",
        modelScale = 1.00,
        scale = 1.00,
        unitSound = "Shade",
        movetp = "hover",
        moveHeight = 50,
    },
    {
        Name = "食尸鬼",
        file = "units\\undead\\Ghoul\\Ghoul",
        modelScale = 1.00,
        scale = 1.00,
        unitSound = "Ghoul",
    },
    {
        Name = "憎恶",
        file = "units\\undead\\Abomination\\Abomination",
        modelScale = 0.90,
        scale = 2.10,
        unitSound = "Abomination",
    },
    {
        Name = "绞肉车",
        file = "units\\undead\\MeatWagon\\MeatWagon",
        modelScale = 0.90,
        scale = 2.40,
        unitSound = "MeatWagon",
    },
    {
        Name = "穴居恶魔",
        file = "units\\undead\\CryptFiend\\CryptFiend",
        modelScale = 0.90,
        scale = 1.90,
        unitSound = "CryptFiend",
    },
    {
        Name = "石像鬼",
        file = "units\\undead\\Gargoyle\\Gargoyle",
        modelScale = 1.00,
        scale = 1.25,
        unitSound = "Gargoyle",
        movetp = "fly",
        moveHeight = 150,
    },
    {
        Name = "女妖",
        file = "units\\undead\\Banshee\\Banshee",
        modelScale = 1.00,
        scale = 1.00,
        unitSound = "Banshee",
        movetp = "hover",
        moveHeight = 50,
    },
}